### ISSUE TITLE
Upgrading to Mediawiki 1.35 seems to have broken something

### ISSUE THREAD

**Issue by tomhughes** [osmfoundation/osmf-mediawiki-skin#24]
Something seems to have gone a bit awry with this skin after the wiki was upgraded from 1.34 to 1.35:

![image](https://user-images.githubusercontent.com/147741/133886785-db34aebb-ab13-431e-b320-e1ea403fd441.png)

**Comment by Firefishy** [comment]
@harry-wood @nebulon42 Could you look at this?

**Comment by harry-wood** [comment]
We could do a quick fix like this: https://github.com/osmfoundation/osmf-mediawiki-skin/pull/25  Or just configure the default skin to 'vector' https://wiki.osmfoundation.org/?useskin=vector  but to actually fix our nice custom skin, someone'll need to spend a bit longer digging into it.

**Comment by Firefishy** [comment]
The colour fix helps

**Comment by nebulon42** [comment]
Basically the skin needs to be rewritten from scratch since Vector moved from PHP to Mustache templates.
I invested a few hours and explored two approaches. One would be to stay with the PHP Template and just update it. This approach is still used by strapping (https://github.com/wikimedia/mediawiki-skins-mediawiki-strapping). The other maybe more future-proof approach would be to switch over to Mustache templates.

With the first approach I ran into an error with output (output was cut-off) which I couldn't resolve till now. When I replaced the PHP template file with the strapping one output worked, but I didn't check whether this was still functional.
With the second approach I did not find any documentation on how it would be possible to make a child skin and my tries with the templates did not result in my modifications being applied.

I fear this would take quite some more time which I currently do not have. Best bet for now would be to downgrade (if that is even possible) or to switch over to Vector or other skin and just replace the logo. In the long run Mediawiki does not lend itself easily to a pleasing visual appearance so maybe another content system would be better here if a nice visual representation is needed.

**Comment by p-starvin** [comment]
Hi @tomhughes @Firefishy @harry-wood & @nebulon42, 

A colleague of mine saw [your tweet](https://twitter.com/OSM_Tech/status/1440403796476055559) and passed it along to me. I think we, [WikiTeq](https://www.wikiteq.com/), might be able to help out here. 

@tomhughes & @Firefishy , are you still looking for assistance on this? 

If you're wanting for a more modern, visually pleasing look it might be worth looking into the Chameleon skin. It's Bootstrap compatible so styling page elements can be done quickly. We use it on our [demonstration wiki ](https://demo.wikiteq.com/wiki/Main_Page). If anyone would like to browser our demo wiki just let me know and I'll create logins. 

-Patrick

**Comment by mikelmaron** [comment]
@p-starvin Thank you for offering help. Yes we can still need assistance. We had been thinking about this as a volunteer effort, not sure what you had in mind. I'd be happy to take a look at the demo, and talk through how you might help.

**Comment by p-starvin** [comment]
@mikelmaron We are a professional company and we typically work for a standard development rate. That being said we enjoy using OpenStreetMaps and understand the project's importance to the world. Compensation is important to "keep the lights on" but our main goal is to help people utilize MediaWiki to spread quality knowledge. 

Would you, and potentially other members from the OpenStreetMaps team, be interested in meeting with our CTO and I?  If so, feel free to schedule a meeting with us [here](https://calendly.com/wikiteq). 

If this doesn't sound like something you're interested in, not a problem. We wish you the best of luck either way and will continue to be users.

**Comment by jdlrobson** [comment]
Do you still need help with this?

It's broken because skins are not designed to be extended.

Should be relatively straightforward to fix this by making this work without Vector. Happy to help out if so.

**Comment by tomhughes** [comment]
Yes this still needs to be fixed properly - there is a temporary hack in place currently to make it vaguely readable but we'd like to get the old layout back.

**Comment by jdlrobson** [comment]
Do you have any screenshots or links to old versions of the site that show it used to look?

**Comment by tomhughes** [comment]
I don't have screenshots, but the wayback machine has old versions like http://web.archive.org/web/20210901050536/https://wiki.osmfoundation.org/wiki/Main_Page.

**Comment by jdlrobson** [comment]
Okay done!

https://github.com/osmfoundation/osmf-mediawiki-skin/pull/26 should get this better than how it was before :)

**Comment by nebulon42** [comment]
@jdlrobson thanks for taking this on.

**Comment by mikelmaron** [comment]
Thank you @jdlrobson !
